title: Palak Agarwal # your name (or website title) here
logo: "/images/PalakAgarwal_Headshot3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Geospatial Data Scientist    
  <br>
  University of Pennsylvania 
  <br>
  Master of Landscape Architecture 
  <br>
  Master of Urban Spatial Analytics
  <br><br>
  Landscape and urban designer           
  bitten by the data bug.
  <br><br>
  <a href="https://www.linkedin.com/in/palak-agarwal-025a68191/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
